### ISSUE TITLE
Thank you sharing your project on awesome-docker

### ISSUE THREAD

**Issue by veggiemonk** [roquie/smalte#1]
Hi @roquie ,

Thank you very much for sharing your project!
The project has been added to the list. Congratulations!

I wanted to contribute to your project because I think it is very useful!

Here are a few suggestion:
* Instead of 
```
Is a dead simple and lightweight template engine. Specially designed for configure services (or application) before start in Docker
```
what do you think of 
```
Dynamically configure applications that require static configuration in docker container
``` 

* in the `README.md`, the example is a bit complicated to understand. Can you elaborate a bit more by showing a few steps ?
For example:
1. create a conf.tmpl (show the file with $VARS in it)
1. create a start script (show the start script)
1. create a Dockerfile (show the Dockerfile)
1. show how to run the service with overwritten values (`docker run --rm -e "VARS=abc" mycontainer`)

What do you think ?

**Comment by roquie** [comment]
Okay, give me some time.

**Comment by roquie** [comment]
Completed:
https://github.com/roquie/smalte/blob/roquie-patch-1/README.md

It's okay?

**Comment by veggiemonk** [comment]
@roquie It's very good! Good job
